-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME 
FROM ANIMAL_INS AS I LEFT OUTER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME NOT LIKE "Intact%" AND I.SEX_UPON_INTAKE LIKE "Intact%"
ORDER BY O.ANIMAL_ID
