-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, O.TOTAL_SALES * P.PRICE AS SALES
FROM 
    PRODUCT P, 
    (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
        FROM OFFLINE_SALE 
        GROUP BY PRODUCT_ID
    ) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE