-- 코드를 입력하세요
SELECT 
    U.USER_ID, 
    U.NICKNAME,
    CONCAT(U.CITY, CONCAT(' ', CONCAT(STREET_ADDRESS1, CONCAT(' ', STREET_ADDRESS2)))) 전체주소,
    CONCAT(SUBSTR(U.TLNO, 0, 3), CONCAT('-', CONCAT(SUBSTR(U.TLNO, 4, 4), CONCAT('-', SUBSTR(U.TLNO, 8)))))
FROM 
    USED_GOODS_USER U, 
    (
        SELECT WRITER_ID
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(*) >= 3
    ) B
WHERE B.WRITER_ID = U.USER_ID 
ORDER BY U.USER_ID DESC
