SELECT APNT_NO, PT_NAME, PT_NO, B.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT A
    JOIN APPOINTMENT B USING (PT_NO)
    JOIN DOCTOR C ON B.MDDR_ID = C.DR_ID
WHERE 1=1
    AND DATE_FORMAT(APNT_YMD,'%Y-%m-%d') = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
    AND B.MCDP_CD = 'CS'
ORDER BY APNT_YMD;