-- 코드를 작성해주세요
SELECT SUM(FISH_COUNT) FISH_COUNT
FROM 
    (
        SELECT N.FISH_NAME, COUNT(*) FISH_COUNT
        FROM FISH_INFO F, FISH_NAME_INFO N
        WHERE F.FISH_TYPE = N.FISH_TYPE
        GROUP BY N.FISH_NAME
    ) A
WHERE FISH_NAME IN ('BASS', 'SNAPPER')